name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v24.7.0'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "mantikora_band@gmail.com"
          git config --global user.name "mantikora-pl"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/mantikora_pl/mantikora_pl.github.io.git
      
      

      - name: Build and deploy
        run: npm run deploy -- --branch gh-pages
